version: '2'
services:
  procurement-app:
    image: procurement
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://procurement-postgresql:5432/procurement
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  procurement-postgresql:
    extends:
      file: postgresql.yml
      service: procurement-postgresql
